"""A fixture workspace expressed as SERVED PAYLOADS, not files.

The TUI's only input is the dashboard service's JSON, so its fixture is that
JSON. Every payload below is shaped after the real endpoint that produces it
(``tests/test_dashboard_server.py`` builds the same shapes from a workspace
tree; ``zicato.query`` is where the keys are defined), and
``test_tui_wire_fidelity.py`` proves the shapes still match the live service.

Two states are provided: :data:`PAYLOADS` (a settled epoch with a full gate,
reflection and board) and :func:`live_payloads` (a round in flight), so the
live-view lenses are exercised without ever running ``zicato evolve``.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any

EPOCH = "2026-07-04_e2"
CHAMPION = "v3"
CHALLENGER = "v4"

PAYLOADS: dict[str, Any] = {
    "/api/health": {
        "status": "ok",
        "version": "0.3.0",
        "uptime_seconds": 91,
        "read_only": True,
        "workspace": "/tmp/ws/.zicato",
        "port": 7892,
        "build": "dev",
    },
    "/api/workspace": {
        "current_epoch_id": EPOCH,
        "epochs": [
            {
                "epoch_id": EPOCH,
                "goal": "cut planner drift on the long-horizon board",
                "best_scalar": 0.0412,
                "best_generation_id": CHAMPION,
                "generation_count": 5,
                "promoted_count": 2,
                "closed": False,
                "parent_epoch_id": None,
            }
        ],
        "sparkline": [{"epoch_id": EPOCH, "scalar": 0.0412}],
        "ledger": [],
    },
    f"/api/epoch?epoch={EPOCH}": {
        "epoch_id": EPOCH,
        "contract_hash": "9f2c41ab77de",
        "closed": False,
        "goal": "cut planner drift on the long-horizon board",
        "brief": "prefer fewer, larger planner edits",
        "harness": {"entrypoint": "agent.py", "mutable_trees": ["agent/"]},
        "board": [
            {
                "entry_id": "plan-long-1",
                "kind": "single",
                "input_preview": "plan a 6-step refactor",
                "expectation_kind": "rubric",
                "budget_s": 90.0,
                "weight": 1.0,
                "tags": ["facet:planning"],
            },
            {
                "entry_id": "plan-long-2",
                "kind": "multi",
                "input_preview": "recover from a failed step",
                "expectation_kind": "predicate",
                "budget_s": 120.0,
                "weight": 1.5,
                "tags": ["facet:recovery", "holdout"],
            },
        ],
        "scoring": {"weights": {"drift_loss": 1.0}},
        "board_split": {
            "configured": True,
            "enabled": True,
            "holdout_fraction": 0.25,
            "holdout_tags": ["holdout"],
            "entries": [
                {"entry_id": "plan-long-1", "slice": "train", "weight": 1.0},
                {"entry_id": "plan-long-2", "slice": "holdout", "tag": "holdout", "weight": 1.5},
            ],
            "train_count": 1,
            "holdout_count": 1,
            "total": 2,
        },
        "mutations": [
            {
                "id": "m1",
                "kind": "prompt",
                "file": "agent/plan.md",
                "lines": "12-30",
                "preview": "…",
            }
        ],
        "experiments": [
            {
                "generation_id": CHALLENGER,
                "parent_generation_id": CHAMPION,
                "proposed_at": "2026-07-04T09:12:00Z",
                "decision": "promoted",
                "promoted": True,
                "patches": {"agent/plan.md": "…"},
                "outcome": {"delta_scalar": -0.0121},
                "hypothesis": "fewer, larger planner edits reduce recovery drift",
            },
            {
                "generation_id": "v5",
                "parent_generation_id": CHALLENGER,
                "proposed_at": "2026-07-04T10:40:00Z",
                "decision": "rejected",
                "promoted": False,
                "patches": {},
                "outcome": {"delta_scalar": 0.0038},
            },
        ],
        "current_champion": CHALLENGER,
        "holdout": {
            "train_scalar": 0.0391,
            "holdout_scalar": 0.0468,
            "budget_remaining": 6,
        },
        "delta_scalar_summary": {"champion_spine": -0.0121, "gross": -0.0083},
        "journal": "",
        "analysis_md": "",
        "analysis_html_available": False,
        "analysis_html_inline": "",
    },
    f"/api/epoch/{EPOCH}/trajectory": {
        "epoch_id": EPOCH,
        "points": [
            {"generation_id": "v0", "scalar": 0.0712, "namespace_values": {}},
            {"generation_id": "v1", "scalar": 0.0668, "namespace_values": {}},
            {"generation_id": "v2", "scalar": 0.0601, "namespace_values": {}},
            {"generation_id": CHAMPION, "scalar": 0.0533, "namespace_values": {}},
            {"generation_id": CHALLENGER, "scalar": 0.0412, "namespace_values": {}},
        ],
        "promotion_rate": 0.4,
        "promoted_count": 2,
        "challenger_count": 5,
        "settled_count": 5,
        "plateaued": True,
        "plateau_measurable": True,
        "verdict": "plateaued",
        "recent_movement": 0.0121,
        "noise_floor": {
            "generation_id": "v0",
            "runs": 6,
            "max_abs_delta": 0.0044,
            "delta_std": 0.0018,
            "measured_at": "2026-07-03T22:00:00Z",
        },
    },
    f"/api/epoch/{EPOCH}/cost": {
        "epoch_id": EPOCH,
        "per_matchup": [],
        "total_runtime_ms": 5_412_000,
        "total_run_count": 40,
        "total_aborted_count": 1,
        "promoted_count": 2,
        "cost_per_promotion_ms": 2_706_000,
    },
    "/api/live/pipeline": {
        "running": False,
        "stale": False,
        "phase": "idle",
        "epoch_id": EPOCH,
        "round_index": 3,
        "steps": [],
        "active_step": None,
        "decision": "promoted",
        "in_flight": 0,
        "generated_at": "2026-07-04T11:00:00Z",
    },
    "/api/lineage": {
        "generations": [
            {
                "generation_id": "v0",
                "epoch_id": EPOCH,
                "parent_generation_id": None,
                "promoted": None,
                "created_at": "2026-07-04T08:00:00Z",
                "elo": 1500.0,
                "elo_se": 61.0,
                "elo_games": 3,
            },
            {
                "generation_id": CHAMPION,
                "epoch_id": EPOCH,
                "parent_generation_id": "v0",
                "promoted": True,
                "created_at": "2026-07-04T08:50:00Z",
                "elo": 1512.4,
                "elo_se": 34.2,
                "elo_games": 7,
            },
            {
                "generation_id": CHALLENGER,
                "epoch_id": EPOCH,
                "parent_generation_id": CHAMPION,
                "promoted": True,
                "created_at": "2026-07-04T09:12:00Z",
                "elo": 1547.8,
                "elo_se": 29.6,
                "elo_games": 9,
            },
            {
                "generation_id": "v5",
                "epoch_id": EPOCH,
                "parent_generation_id": CHALLENGER,
                "promoted": False,
                "created_at": "2026-07-04T10:40:00Z",
                "elo": 1488.0,
                "elo_se": 77.0,
                "elo_games": 2,
            },
        ]
    },
    "/api/tournaments": {
        "epoch_id": EPOCH,
        "structure": "gauntlet",
        "structure_params": {},
        "champion_lineage": ["v0", CHAMPION, CHALLENGER],
        "matchups": [
            {
                "champion": "v0",
                "challenger": CHAMPION,
                "decision": "promoted",
                "delta_scalar": -0.0179,
                "rejection_reason": None,
                "hypothesis_core_idea": "shorten the plan preamble",
                "ran_at": "2026-07-04T08:50:00Z",
            },
            {
                "champion": CHAMPION,
                "challenger": CHALLENGER,
                "decision": "promoted",
                "delta_scalar": -0.0121,
                "rejection_reason": None,
                "hypothesis_core_idea": "fewer, larger planner edits",
                "ran_at": "2026-07-04T09:12:00Z",
            },
            {
                "champion": CHALLENGER,
                "challenger": "v5",
                "decision": "rejected",
                "delta_scalar": 0.0038,
                "rejection_reason": "recovery namespace regressed",
                "hypothesis_core_idea": "cache the plan across steps",
                "ran_at": "2026-07-04T10:40:00Z",
            },
        ],
        "tournaments": [],
    },
    "/api/active-tournament": {
        "tournament_id": None,
        "epoch_id": EPOCH,
        "phase": "idle",
        "structure": "gauntlet",
        "structure_params": {},
        "competitors": [],
        "rounds": [],
        "standings": [],
        "field_status": [],
        "entries": [],
        "projected": {},
    },
    f"/api/round/{EPOCH}/{CHAMPION}/{CHALLENGER}/gate": {
        "decision": "promoted",
        "delta_scalar": -0.0121,
        "delta_pass_rate": 0.05,
        "margin": 0.005,
        "champion_scalar": 0.0533,
        "challenger_scalar": 0.0412,
        "reason": "scalar improved past the promote margin with no namespace regression",
        "deciding_rule": "scalar_margin",
        "regressed_predicate": None,
        "regressed_namespace": None,
        "primary_driver": {"judge": "plan_coherence"},
        "live": None,
        "override": {"present": False},
        "rating": {
            "present": True,
            "p_stronger": 0.94,
            "threshold": 0.9,
            "champion": {"theta": -0.12, "se": 0.09, "ci_lo": -0.30, "ci_hi": 0.06},
            "challenger": {"theta": 0.31, "se": 0.08, "ci_lo": 0.15, "ci_hi": 0.47},
        },
        "rules": [
            {
                "id": "no_regression",
                "label": "no namespace regressed",
                "status": "pass",
                "fired": False,
                "detail": "0 of 4 namespaces regressed",
            },
            {
                "id": "scalar_margin",
                "label": "scalar beat the promote margin",
                "status": "pass",
                "fired": True,
                "detail": "Δ -0.0121, needs ≤ -0.0050",
            },
            {
                "id": "holdout_veto",
                "label": "holdout did not veto",
                "status": "pass",
                "fired": False,
                "detail": "holdout Δ -0.0074",
            },
        ],
    },
    f"/api/generation/{EPOCH}/{CHALLENGER}/per-entry": {
        "epoch_id": EPOCH,
        "generation_id": CHALLENGER,
        "tournament_id": f"{EPOCH}:{CHAMPION}:{CHALLENGER}",
        "mean_score": 0.71,
        "facet_scores": {
            "facets": {
                "planning": {
                    "scalar": 0.0388,
                    "mean_score": 0.74,
                    "scored_count": 1,
                    "entry_count": 1,
                },
                "recovery": {
                    "scalar": 0.0461,
                    "mean_score": 0.68,
                    "scored_count": 1,
                    "entry_count": 1,
                },
            },
            "overall": {
                "scalar": 0.0412,
                "mean_score": 0.71,
                "scored_count": 2,
                "entry_count": 2,
            },
        },
        "entries": [
            {
                "entry_id": "plan-long-1",
                "run_id": "r-8841",
                "drift_loss": 0.0388,
                "pass_fail": True,
                "runtime_ms": 41_200,
                "wall_clock_budget_exceeded": False,
                "match_id": None,
                "rung": None,
            },
            {
                "entry_id": "plan-long-2",
                "run_id": "r-8842",
                "drift_loss": 0.0461,
                "pass_fail": False,
                "runtime_ms": 121_800,
                "wall_clock_budget_exceeded": True,
                "match_id": None,
                "rung": None,
            },
        ],
    },
    f"/api/generation/{EPOCH}/{CHALLENGER}/per-judge": {
        "epoch_id": EPOCH,
        "generation_id": CHALLENGER,
        "judges": [
            {
                "judge_name": "plan_coherence",
                "weighted_loss": 0.0244,
                "raw_loss": 0.0244,
                "run_count": 2,
                "weight": 1.0,
            },
            {
                "judge_name": "tool_discipline",
                "weighted_loss": 0.0168,
                "raw_loss": 0.0336,
                "run_count": 2,
                "weight": 0.5,
            },
        ],
    },
    f"/api/epoch/{EPOCH}/eval-health": {
        "epoch_id": EPOCH,
        "found": True,
        "mde": {
            "floor_measured": True,
            "floor": 0.0044,
            "replicates": 3,
            "usable": True,
            "formula_n": 3,
            "df": 4,
            "mde": 0.0121,
            "mde_relaxed": 0.0098,
            "alpha": 0.05,
            "alpha_relaxed": 0.1,
            "power": 0.8,
            "formula": "MDE = (t+t)·sd·sqrt(2/n)",
            "note": None,
        },
        "noisiest": [{"entry_id": "plan-long-2", "flip_rate": 0.33}],
        "dead": [{"entry_id": "plan-long-1", "reason": "every candidate passes"}],
        "insufficient": [],
        "runtime_cost": [],
        "holdout_budget": {"budget": 10, "spent": 4},
        "rotation": {
            "rotate_holdout": True,
            "max_generations_per_contract": 6,
            "evaluated_generations": 5,
            "refresh_recommended": True,
            "recommendation": "rotate the holdout before the next contract roll",
        },
        "redundancy": {"available": True, "clusters": [{"entries": ["plan-long-1"]}], "note": None},
    },
    f"/api/epoch/{EPOCH}/evals": {
        "epoch_id": EPOCH,
        "found": True,
        "candidates": [{"generation_id": CHAMPION}, {"generation_id": CHALLENGER}],
        "entries": [
            {
                "entry_id": "plan-long-1",
                "slice": "train",
                "tag": None,
                "flip_rate": 0.0,
                "flip_rate_measured": True,
                "calibration_runs": 6,
                "calibration_generation": CHAMPION,
            },
            {
                "entry_id": "plan-long-2",
                "slice": "holdout",
                "tag": "holdout",
                "flip_rate": 0.33,
                "flip_rate_measured": True,
                "calibration_runs": 6,
                "calibration_generation": CHAMPION,
            },
        ],
        "cells": [
            [
                {
                    "drift_loss": 0.041,
                    "pass_ratio": 1.0,
                    "pass_fail": True,
                    "score": 0.72,
                    "replicates": 3,
                    "cached": False,
                },
                {
                    "drift_loss": 0.0388,
                    "pass_ratio": 1.0,
                    "pass_fail": True,
                    "score": 0.74,
                    "replicates": 3,
                    "cached": False,
                },
            ],
            [
                {
                    "drift_loss": 0.052,
                    "pass_ratio": 0.33,
                    "pass_fail": False,
                    "score": 0.61,
                    "replicates": 3,
                    "cached": False,
                },
                None,
            ],
        ],
        "calibration": {
            "measured": True,
            "generation_id": CHAMPION,
            "runs": 6,
            "max_abs_delta": 0.0044,
        },
    },
    f"/api/reflections?epoch={EPOCH}": {
        "reflections": [
            {
                "reflection_id": "refl-2026-07-04",
                "epoch_id": EPOCH,
                "created_at": "2026-07-04T11:30:00Z",
                "mode": "adjudicated",
                "executed": True,
                "noise_floor_max_abs_delta": 0.0044,
                "decision_flip_p": 0.08,
                "n_findings": 2,
                "n_judges": 2,
            },
            {
                "reflection_id": "refl-2026-07-01",
                "epoch_id": EPOCH,
                "created_at": "2026-07-01T09:00:00Z",
                "mode": "zero-llm",
                "executed": True,
                "noise_floor_max_abs_delta": None,
                "decision_flip_p": None,
                "n_findings": 0,
                "n_judges": 2,
            },
        ]
    },
    "/api/reflection/refl-2026-07-04/summary": {
        "reflection_id": "refl-2026-07-04",
        "epoch_id": EPOCH,
        "created_at": "2026-07-04T11:30:00Z",
        "mode": "adjudicated",
        "executed": True,
        "found": True,
        "noise_floor_max_abs_delta": 0.0044,
        "decision_flip_p": 0.08,
        "pillars": {
            "discrimination": {"verdict": "attend", "detail": "one entry never discriminates"},
            "reliability": {"verdict": "sound", "detail": "kappa 0.81 across judges"},
        },
        "findings": [
            {
                "finding_id": "f-dead-entry",
                "severity": "warning",
                "title": "plan-long-1 never discriminates",
                "detail": "every candidate passes this entry; it cannot separate the field.",
                "evidence": [
                    {
                        "judge_name": "plan_coherence",
                        "run_ref": "r-8841:1",
                        "verdict": "TP",
                        "span": "step 3",
                    },
                    {
                        "judge_name": "plan_coherence",
                        "run_ref": "r-8840:1",
                        "verdict": "TP",
                        "span": "step 2",
                    },
                ],
                "proposed_op": {"op": "retire_entry", "args": {"entry_id": "plan-long-1"}},
            },
            {
                "finding_id": "f-judge-fp",
                "severity": "critical",
                "title": "tool_discipline fires falsely on recovery turns",
                "detail": "4 of 9 adjudicated firings were false positives on recovery turns.",
                "evidence": [
                    {
                        "judge_name": "tool_discipline",
                        "run_ref": "r-8842:4",
                        "verdict": "FP",
                        "span": "turn 4",
                    }
                ],
                "proposed_op": {
                    "op": "tighten_judge",
                    "args": {"judge_name": "tool_discipline", "scope": "recovery"},
                },
            },
        ],
        "fidelity_tiers": ["adjudicated", "reconstructed"],
    },
    "/api/reflection/refl-2026-07-04/scorecards": {
        "reflection_id": "refl-2026-07-04",
        "epoch_id": EPOCH,
        "found": True,
        "judges": [
            {
                "judge_name": "plan_coherence",
                "tp": 12,
                "fp": 1,
                "fn": 2,
                "tn": 20,
                "ambiguous": 1,
                "precision": 0.92,
                "recall": 0.86,
                "severity_accuracy": 0.78,
                "disagreement_rate": 0.09,
                "self_consistency_kappa": 0.81,
                "exercised": True,
                "redundant_with": [],
            },
            {
                "judge_name": "tool_discipline",
                "tp": 5,
                "fp": 4,
                "fn": 1,
                "tn": 25,
                "ambiguous": 0,
                "precision": 0.56,
                "recall": 0.83,
                "severity_accuracy": 0.61,
                "disagreement_rate": 0.22,
                "self_consistency_kappa": 0.64,
                "exercised": True,
                "redundant_with": [],
            },
        ],
    },
    "/api/reflection/refl-2026-07-04/practices": {
        "reflection_id": "refl-2026-07-04",
        "epoch_id": EPOCH,
        "found": True,
        "checks": [
            {
                "id": "holdout-held",
                "name": "holdout is never trained on",
                "verdict": "sound",
                "detail": "",
            },
            {
                "id": "floor-measured",
                "name": "the A/A noise floor is measured",
                "verdict": "attend",
                "detail": "measured 3 rounds ago",
            },
        ],
        "verdict_counts": {"sound": 1, "attend": 1, "unsound": 0, "unmeasured": 0},
    },
    "/api/health-report": {
        "epoch_id": EPOCH,
        "findings": [
            {
                "severity": "warning",
                "detector": "board_discrimination",
                "summary": "1 of 2 board entries never discriminates between candidates",
            }
        ],
        "healthy": False,
        "checked_at": "2026-07-04T11:31:00Z",
    },
    "/api/heartbeat": {
        "pid": 8812,
        "instance_id": "default",
        "epoch_id": EPOCH,
        "generation_id": "v5",
        "phase": "idle",
        "round_index": 3,
        "seq": 411,
        "paused": False,
        "ts": "2026-07-04T11:31:02Z",
    },
    "/api/logs?limit=200": {
        "records": [
            {
                "cursor": 1024,
                "level": "info",
                "component": "orchestrator",
                "message": "round 3 promoted v4 over v3",
                "epoch_id": EPOCH,
                "generation_id": CHALLENGER,
                "run_id": None,
            },
            {
                "cursor": 1180,
                "level": "warning",
                "component": "tournament",
                "message": "run r-8842 exceeded its wall-clock budget",
                "epoch_id": EPOCH,
                "generation_id": CHALLENGER,
                "run_id": "r-8842",
            },
        ],
        "cursor": 1180,
        "invocation": "inv-2026-07-04-01",
        "invocations": ["inv-2026-07-04-01"],
        "level": None,
    },
}


def live_payloads() -> dict[str, Any]:
    """The same workspace with a round in flight and a swiss field racing."""
    payloads = deepcopy(PAYLOADS)
    payloads["/api/live/pipeline"] = {
        "running": True,
        "stale": False,
        "phase": "tournament",
        "epoch_id": EPOCH,
        "round_index": 4,
        "steps": [
            {"id": "propose", "label": "propose", "state": "done", "detail": "3 challengers"},
            {"id": "screen", "label": "screen", "state": "done", "detail": "3 applied"},
            {
                "id": "tournament",
                "label": "tournament",
                "state": "running",
                "detail": "rung 1 of 2",
            },
            {"id": "gate", "label": "gate", "state": "pending", "detail": ""},
        ],
        "active_step": "tournament",
        "decision": None,
        "in_flight": 4,
        "generated_at": "2026-07-04T11:40:00Z",
    }
    payloads["/api/tournaments"] = {
        **payloads["/api/tournaments"],
        "structure": "swiss",
        "structure_params": {"rounds": 2},
        "tournaments": [{"tournament_id": "t-4"}],
    }
    payloads["/api/active-tournament"] = {
        "tournament_id": "t-4",
        "epoch_id": EPOCH,
        "phase": "tournament",
        "structure": "swiss",
        "structure_params": {"rounds": 2},
        "competitors": [
            {"generation_id": CHALLENGER, "seed": 1, "role": "champion"},
            {"generation_id": "v6", "seed": 2, "role": "challenger"},
            {"generation_id": "v7", "seed": 3, "role": "challenger"},
        ],
        "entries": [],
        "rounds": [
            {
                "stage_index": 0,
                "label": "round 1",
                "matches": [
                    {
                        "match_id": "r0_m0",
                        "competitors": [CHALLENGER, "v6"],
                        "winner": CHALLENGER,
                        "decision": "promoted",
                        "bye": False,
                        "survivors": [CHALLENGER],
                        "cut": ["v6"],
                    },
                    {
                        "match_id": "r0_m1",
                        "competitors": ["v7"],
                        "winner": None,
                        "decision": None,
                        "bye": True,
                        "survivors": ["v7"],
                        "cut": [],
                    },
                ],
            },
            {"stage_index": 1, "label": "round 2", "matches": []},
        ],
        "standings": [
            {
                "generation_id": CHALLENGER,
                "rank": 1,
                "scalar": 0.0412,
                "wins": 1,
                "losses": 0,
                "draws": 0,
                "points": 1.0,
                "status": "racing",
                "in_flight": False,
            },
            {
                "generation_id": "v7",
                "rank": 2,
                "scalar": None,
                "wins": 0,
                "losses": 0,
                "points": 0.5,
                "status": "",
                "in_flight": True,
                "projected_scalar": 0.0455,
            },
            {
                "generation_id": "v6",
                "rank": 3,
                "scalar": 0.0559,
                "wins": 0,
                "losses": 1,
                "points": 0.0,
                "status": "cut",
                "in_flight": False,
            },
        ],
        "field_status": [
            {"generation_id": "v6", "status": "applied", "reason": "", "mutation_ids": ["m1"]},
            {
                "generation_id": "v7",
                "status": "applied",
                "reason": "",
                "mutation_ids": ["m1", "m2"],
            },
            {
                "generation_id": "v8",
                "status": "rejected",
                "reason": "patch did not apply cleanly",
                "mutation_ids": [],
            },
        ],
        "projected": {},
    }
    payloads["/api/heartbeat"] = {**payloads["/api/heartbeat"], "phase": "tournament", "seq": 490}
    return payloads


__all__ = ["CHALLENGER", "CHAMPION", "EPOCH", "PAYLOADS", "live_payloads"]
