"""The workspace query layer: read-only ``.zicato/`` state assembly.

Library code: these readers turn the on-disk workspace
(runtime state files, the SQLite analytical index, epoch records) into
the JSON view shapes any consumer can render. The dashboard server is
the primary consumer today, but the layer has no dashboard dependency —
:mod:`zicato.query` must never import :mod:`zicato.dashboard` (enforced
by the import-linter contracts).

The readers live in one submodule per view. This package re-exports
every name they define, so a consumer imports from ``zicato.query``
directly and never needs to know which submodule owns a reader.

Every function here is best-effort: a missing or transiently-truncated
file degrades to an empty / ``None`` value rather than raising, so no
endpoint built on top of this ever returns a 500.
"""

from __future__ import annotations

from zicato.query._sqlite import (
    _IndexAbsent,
    _open_index,
    _opt_json,
    _query,
)
from zicato.query.conversations_view import (
    build_matchup_conversations,
)
from zicato.query.decisions import (
    PROMOTED_DECISIONS as _PROMOTED_DECISIONS,
)
from zicato.query.decisions import (
    experiment_decision as _experiment_decision,
)
from zicato.query.epoch_view import (
    _TOURNAMENT_STRUCTURES,
    _board_input_preview,
    _distill_brief_goal,
    _latest_holdout_summary,
    _normalize_structure,
    _overfitting_block_from_scoring,
    _parse_board,
    _parse_mutations,
    _read_epoch_brief,
    _read_epoch_experiments,
    _read_harness,
    _read_text_best_effort,
    _stable_unit,
    _tournament_block_from_scoring,
    build_epoch_analysis,
    build_epoch_view,
    build_epochs_summary,
    compute_board_split,
    compute_epoch_delta_summary,
    read_epoch_analysis_html,
)
from zicato.query.eval_view import (
    _empty_dossier,
    _empty_health,
    _empty_matrix,
    build_eval_dossier,
    build_eval_health,
    build_eval_matrix,
)
from zicato.query.events_index import (
    _CONTRACT_COMPONENT_NAMES,
    _LEDGER_COMPONENT_NAMES,
    _REUSE_RUN_ID_INDEX_CACHE,
    _RUN_ID_INDEX_CACHE,
    _build_reuse_run_id_index,
    _build_run_id_index,
    _epoch_structure,
    _read_contract_components,
    _run_id_of_events_file,
    build_contract_diff,
    build_meta_loop_ledger,
    build_workspace_view,
    find_generation_entry_events,
    find_generation_run,
    find_run_events_path,
    read_run_result,
    resolve_transcript_events,
)
from zicato.query.execution_plan import (
    PlanNode,
    build_execution_plan,
)
from zicato.query.gate_view import (
    _build_scalar_decomposition,
    _drift_counts_for_generation,
    _gen_agg_for_gate,
    _latest_round_report,
    _mean_drift_loss_per_generation,
    _parse_scoring_provenance,
    _read_epoch_scoring_weights,
    _representative_drift_provenance,
    build_drift_movements,
    build_gate_breakdown,
    build_health_report,
    build_rating_view,
    build_score_trajectory,
)
from zicato.query.hypothesis_view import (
    build_calibration_trend,
    build_hypothesis_accuracy,
)
from zicato.query.journal_view import (
    read_epoch_journal,
    read_epoch_journal_md,
)
from zicato.query.judge_roster import (
    _empty_judge_roster,
    build_judge_roster,
)
from zicato.query.judge_view import (
    SEARCH_LIMIT_PER_CATEGORY,
    _collect_judge_names_from_board_file,
    _collect_judge_names_from_index,
    _empty_search_result,
    _load_run_loss,
    _sort_by_match_quality,
    build_environment,
    build_expectation_outcomes_for_run,
    build_per_entry_for_generation,
    build_per_judge_comparison,
    build_per_judge_for_entry,
    build_per_judge_for_generation,
    build_per_judge_for_run,
    build_per_judge_trend,
    build_run_header,
    build_search_results,
    build_workspace_identity,
    resolve_run_id_for_entry,
)
from zicato.query.ledger_view import (
    build_experiments_ledger,
)
from zicato.query.lineage_view import (
    build_lineage_view,
)
from zicato.query.live_execution_plan import (
    build_live_execution_plan,
    build_live_pipeline,
)
from zicato.query.log_stream import (
    LOG_DEFAULT_LIMIT,
    LOG_MAX_LIMIT,
    Invocation,
    build_log_view,
    clamp_log_limit,
    list_invocations,
    resolve_invocation,
    tail_records,
)
from zicato.query.loop_view import (
    build_optimization_trajectory,
    build_round_pipeline,
    build_tournament_cost,
)
from zicato.query.paths import (
    _NUM_RUN,
    _PREVIEW_CHARS,
    WorkspacePaths,
    _epoch_created_at,
    _epoch_sort_key,
    _is_finite,
    _iso,
    _natural_key,
    _parse_iso,
    _preview,
    _read_json_value,
    _resolve_epoch_id,
    _utc_now,
    list_epoch_ids,
    read_current_epoch,
    to_snake,
)
from zicato.query.proposer_view import (
    build_proposer_recommendations,
    build_proposer_scorecard,
)
from zicato.query.racing_view import (
    build_racing_field,
)
from zicato.query.reflection_view import (
    build_adjudication_xray,
    build_judge_scorecards,
    build_practice_review,
    build_reflection_summary,
    entry_candidate_matrix,
    list_reflections,
)
from zicato.query.rounds_view import (
    build_round_timeline,
)
from zicato.query.run_log import (
    RUN_LOG_DEFAULT_LIMIT,
    RUN_LOG_MAX_LIMIT,
    _event_cursor,
    _newest_active_run_events,
    _newest_epoch_events,
    _summarize,
    _tail_events,
    build_run_log,
    clamp_run_log_limit,
    locate_events_file,
)
from zicato.query.runtime_view import (
    _ENTRY_STATUS_CANONICAL,
    LIVENESS_INTERRUPTED,
    LIVENESS_LIVE,
    LIVENESS_SETTLED,
    STALE_HEARTBEAT_S,
    _compute_run_progress,
    _heartbeat_file_mtime_iso,
    _normalize_tournament_statuses,
    build_snapshot,
    derive_liveness,
    is_active_phase,
    normalize_entry_status,
    read_active_runs_view,
    read_active_tournament_dict,
    read_adk_session_id_from_events,
    read_effective_settings,
    read_heartbeat_dict,
    read_lock_dict,
    read_meta_loop_session_id,
    read_paused,
)
from zicato.query.tournament_view import (
    _champion_lineage,
    _decode_crowning_pair,
    _empty_tournament_structure,
    _enrich_field_status,
    _entry_outcome,
    _is_field_tournament_id,
    _opt_metrics,
    _opt_score,
    _read_gen_score,
    _read_run_loss_files,
    _structure_from_active,
    _structure_from_index,
    _structure_from_loss_files,
    _tournament_id_for,
    _verdict,
    attach_elim_states,
    build_bracket,
    build_matchup_detail,
    build_matchup_grid,
    build_tournament_structure,
    derive_elim_states,
)
from zicato.query.trace_view import (
    _empty_provenance,
    build_suggestion_provenance,
    build_trace_detail,
    build_trace_list,
)
from zicato.query.transcript_view import (
    FIDELITY_EVENTS,
    build_run_transcript,
    build_run_transcript_delta,
    empty_run_transcript,
    empty_run_transcript_delta,
    resolve_conversation,
)

__all__ = [
    "PlanNode",
    "RUN_LOG_DEFAULT_LIMIT",
    "RUN_LOG_MAX_LIMIT",
    "SEARCH_LIMIT_PER_CATEGORY",
    "WorkspacePaths",
    "_CONTRACT_COMPONENT_NAMES",
    "_ENTRY_STATUS_CANONICAL",
    "_IndexAbsent",
    "_LEDGER_COMPONENT_NAMES",
    "_NUM_RUN",
    "_PREVIEW_CHARS",
    "_PROMOTED_DECISIONS",
    "_REUSE_RUN_ID_INDEX_CACHE",
    "_RUN_ID_INDEX_CACHE",
    "_TOURNAMENT_STRUCTURES",
    "_board_input_preview",
    "_build_reuse_run_id_index",
    "_build_run_id_index",
    "_build_scalar_decomposition",
    "_champion_lineage",
    "_collect_judge_names_from_board_file",
    "_collect_judge_names_from_index",
    "_compute_run_progress",
    "_decode_crowning_pair",
    "_distill_brief_goal",
    "_drift_counts_for_generation",
    "_empty_dossier",
    "_empty_health",
    "_empty_judge_roster",
    "_empty_matrix",
    "_empty_provenance",
    "_empty_search_result",
    "_empty_tournament_structure",
    "_enrich_field_status",
    "_entry_outcome",
    "_epoch_created_at",
    "_epoch_sort_key",
    "_epoch_structure",
    "_event_cursor",
    "_experiment_decision",
    "_gen_agg_for_gate",
    "_heartbeat_file_mtime_iso",
    "_is_field_tournament_id",
    "_is_finite",
    "_iso",
    "_latest_holdout_summary",
    "_latest_round_report",
    "_load_run_loss",
    "_mean_drift_loss_per_generation",
    "_natural_key",
    "_newest_active_run_events",
    "_newest_epoch_events",
    "_normalize_structure",
    "_normalize_tournament_statuses",
    "_open_index",
    "_opt_json",
    "_opt_metrics",
    "_opt_score",
    "_overfitting_block_from_scoring",
    "_parse_board",
    "_parse_iso",
    "_parse_mutations",
    "_parse_scoring_provenance",
    "_preview",
    "_query",
    "_read_contract_components",
    "_read_epoch_brief",
    "_read_epoch_experiments",
    "_read_epoch_scoring_weights",
    "_read_gen_score",
    "_read_harness",
    "_read_json_value",
    "_read_run_loss_files",
    "_read_text_best_effort",
    "_representative_drift_provenance",
    "_resolve_epoch_id",
    "_run_id_of_events_file",
    "_sort_by_match_quality",
    "_stable_unit",
    "_structure_from_active",
    "_structure_from_index",
    "_structure_from_loss_files",
    "_summarize",
    "_tail_events",
    "_tournament_block_from_scoring",
    "_tournament_id_for",
    "_utc_now",
    "_verdict",
    "attach_elim_states",
    "build_bracket",
    "build_contract_diff",
    "build_drift_movements",
    "build_environment",
    "build_epoch_view",
    "build_execution_plan",
    "build_epochs_summary",
    "build_calibration_trend",
    "build_expectation_outcomes_for_run",
    "build_experiments_ledger",
    "build_gate_breakdown",
    "build_hypothesis_accuracy",
    "build_rating_view",
    "build_health_report",
    "build_lineage_view",
    "build_live_execution_plan",
    "build_live_pipeline",
    "build_matchup_detail",
    "build_matchup_grid",
    "build_meta_loop_ledger",
    "build_optimization_trajectory",
    "build_proposer_recommendations",
    "build_proposer_scorecard",
    "build_racing_field",
    "build_reflection_summary",
    "build_judge_roster",
    "build_judge_scorecards",
    "build_practice_review",
    "build_adjudication_xray",
    "entry_candidate_matrix",
    "list_reflections",
    "build_eval_matrix",
    "build_eval_dossier",
    "build_eval_health",
    "build_round_timeline",
    "build_suggestion_provenance",
    "build_trace_detail",
    "build_trace_list",
    "build_per_entry_for_generation",
    "build_round_pipeline",
    "build_per_judge_comparison",
    "build_per_judge_for_entry",
    "build_per_judge_for_generation",
    "build_epoch_analysis",
    "build_matchup_conversations",
    "build_per_judge_for_run",
    "build_per_judge_trend",
    "build_run_header",
    "build_run_log",
    "build_log_view",
    "list_invocations",
    "resolve_invocation",
    "tail_records",
    "clamp_log_limit",
    "LOG_DEFAULT_LIMIT",
    "LOG_MAX_LIMIT",
    "Invocation",
    "build_score_trajectory",
    "build_search_results",
    "LIVENESS_INTERRUPTED",
    "LIVENESS_LIVE",
    "LIVENESS_SETTLED",
    "STALE_HEARTBEAT_S",
    "build_snapshot",
    "derive_liveness",
    "is_active_phase",
    "build_tournament_cost",
    "build_tournament_structure",
    "derive_elim_states",
    "build_workspace_identity",
    "build_workspace_view",
    "clamp_run_log_limit",
    "compute_board_split",
    "compute_epoch_delta_summary",
    "find_generation_entry_events",
    "FIDELITY_EVENTS",
    "build_run_transcript",
    "build_run_transcript_delta",
    "empty_run_transcript",
    "empty_run_transcript_delta",
    "find_generation_run",
    "find_run_events_path",
    "list_epoch_ids",
    "locate_events_file",
    "normalize_entry_status",
    "read_active_runs_view",
    "read_active_tournament_dict",
    "read_adk_session_id_from_events",
    "read_current_epoch",
    "read_epoch_analysis_html",
    "read_epoch_journal",
    "read_epoch_journal_md",
    "read_run_result",
    "read_effective_settings",
    "read_heartbeat_dict",
    "read_lock_dict",
    "read_meta_loop_session_id",
    "read_paused",
    "resolve_conversation",
    "resolve_run_id_for_entry",
    "resolve_transcript_events",
    "to_snake",
]
